# Generated by Django 3.1.5 on 2021-01-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('max_power', models.FloatField(help_text='maximum power in Kw')),
                ('host', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InverterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('brand_type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('forecast_api_key', models.CharField(blank=True, max_length=255)),
                ('forecast_provider', models.CharField(default='solcast', max_length=128)),
                ('latitude', models.FloatField(help_text='maximum power in Kw')),
                ('longitude', models.FloatField(help_text='maximum power in Kw')),
                ('influxdb_host', models.GenericIPAddressField(blank=True, null=True)),
                ('influxdb_database', models.CharField(default='solar', max_length=64)),
                ('influxdb_port', models.IntegerField(default=8086)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('power_per_panel', models.FloatField(help_text='power for single panel in kw')),
                ('number_of_panels', models.IntegerField(help_text='number of panel with same orientation and tilt')),
                ('tilt', models.IntegerField(help_text='0 is horizontal, 90 is vertical positoned')),
                ('azimuth', models.IntegerField(help_text='-180 is north, -90 is east, 0 is south and 90 is west')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.inverter')),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='inverter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.invertertype'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.system'),
        ),
    ]
