# Generated by Django 3.1.4 on 2021-01-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='forecast_api_key',
            field=models.CharField(blank=True, help_text='api key from solar forecast provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='forecast_provider',
            field=models.CharField(default='solcast', help_text='solar forecast provider', max_length=128),
        ),
        migrations.AlterField(
            model_name='system',
            name='influxdb_database',
            field=models.CharField(default='solar', help_text='Reporting database name', max_length=64),
        ),
        migrations.AlterField(
            model_name='system',
            name='influxdb_host',
            field=models.GenericIPAddressField(blank=True, help_text='Reporting database host ip address', null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='influxdb_port',
            field=models.IntegerField(default=8086, help_text='Reporting database port'),
        ),
        migrations.AlterField(
            model_name='system',
            name='latitude',
            field=models.FloatField(help_text='location of the system'),
        ),
        migrations.AlterField(
            model_name='system',
            name='longitude',
            field=models.FloatField(help_text='location of the system'),
        ),
    ]
